import base64
import logging
import os

import anthropic
from google import genai
from google.genai import types

from models import DetectionResult

logger = logging.getLogger(__name__)

# Cost per 1M tokens: (input, output)
_MODEL_COSTS: dict[str, tuple[float, float]] = {
    "gemini-2.5-flash-lite":       (0.10, 0.40),
    "gemini-2.5-flash":            (0.30, 1.00),
    "claude-haiku-4-5-20251001":   (0.80, 4.00),
}

_SAFETY_SETTINGS = [
    types.SafetySetting(category="HARM_CATEGORY_HARASSMENT",        threshold="BLOCK_NONE"),
    types.SafetySetting(category="HARM_CATEGORY_HATE_SPEECH",       threshold="BLOCK_NONE"),
    types.SafetySetting(category="HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold="BLOCK_NONE"),
    types.SafetySetting(category="HARM_CATEGORY_DANGEROUS_CONTENT", threshold="BLOCK_NONE"),
]

# Lazy singletons
_gemini_client: genai.Client | None = None
_claude_client: anthropic.AsyncAnthropic | None = None


def _get_gemini() -> genai.Client:
    global _gemini_client
    if _gemini_client is None:
        _gemini_client = genai.Client()
    return _gemini_client


def _get_claude() -> anthropic.AsyncAnthropic:
    global _claude_client
    if _claude_client is None:
        _claude_client = anthropic.AsyncAnthropic()
    return _claude_client


# ---------------------------------------------------------------------------
# Caption pre-screening — keyword-based signal before any vision call
# ---------------------------------------------------------------------------

# Phrases that near-definitively confirm AI-generated content
_CAPTION_STRONG_AI = [
    "ai generated", "ai-generated", "made with ai", "made by ai", "created by ai",
    "ai video", "ai or real", "ai vs real", "is this ai", "real or ai",
    "ai footage", "ai content", "ai challenge", "ai showcase",
    "sora", "runway ml", "pika labs", "kling ai", "luma ai", "vidu",
    "stable diffusion", "midjourney video", "deepfake", "synthetic video",
    "ai created", "generated by ai", "ai tools", "using ai",
]

# Words that weakly suggest AI involvement
_CAPTION_WEAK_AI = [
    " ai ", "#ai", "artificial", "generated", "synthetic", "avatar",
    "virtual human", "digital human", "cgi", "vfx",
]


def _caption_signal(caption: str | None) -> str:
    """
    Returns 'STRONG' | 'WEAK' | 'NONE' based on caption keywords.
    STRONG = caption near-definitively confirms AI content.
    """
    if not caption:
        return "NONE"
    lower = caption.lower()
    if any(kw in lower for kw in _CAPTION_STRONG_AI):
        return "STRONG"
    if any(kw in lower for kw in _CAPTION_WEAK_AI):
        return "WEAK"
    return "NONE"


# ---------------------------------------------------------------------------
# Prompt construction — multi-signal structured reasoning
# ---------------------------------------------------------------------------

_PROMPT_TEMPLATE = """\
You are an expert forensic analyst specialising in detecting AI-generated video content.
Your job is to analyse every available signal and reason through them step-by-step before giving a final verdict.

{caption_block}\
{audio_hint}\
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SIGNAL 1 — CAPTION ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{caption_analysis_instruction}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SIGNAL 2 — VISUAL FRAME ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Examine the provided video frames carefully. Look for:
• Unnatural skin texture — waxy, overly smooth, or plastic-looking
• Face morphing, blending, or flickering between frames
• Inconsistent lighting — shadows or reflections that don't match the scene
• Background distortion — blurred, warped, or geometrically wrong elements
• Hair, teeth, or fine details that look artificial or inconsistent frame-to-frame
• Eye reflections that don't match real light sources
• Unnatural motion — interpolated movement, impossible physics
• Garbled or morphing text within the video
• Hands with wrong finger count or distorted joints
• General uncanny valley quality

State your visual assessment before the final verdict.

{audio_signal_block}\
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SYNTHESIS — COMBINE ALL SIGNALS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Weigh all signals together using these rules:
• If the caption EXPLICITLY mentions AI generation, AI tools, or an "AI or Real" challenge → treat as near-definitive AI evidence (HIGH weight)
• If visual frames show clear AI artifacts → strong visual confirmation
• If signals conflict, explain why and lean toward the stronger signal
• Do NOT let realistic-looking visuals override a caption that explicitly confirms AI generation

Respond using EXACTLY this format and nothing else:
VERDICT: [AI GENERATED / LIKELY REAL / UNCERTAIN]
CONFIDENCE: [HIGH / MEDIUM / LOW]
REASON: [One sentence citing the strongest combined signal(s)]\
"""

_CAPTION_ANALYSIS_WITH_SIGNAL = """\
Caption: "{caption}"
Caption AI signal detected: {signal_label}
{signal_instruction}\
"""

_AUDIO_SIGNAL_BLOCK = """\
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SIGNAL 3 — AUDIO ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Listen to the provided audio for:
• Robotic, overly smooth, or unnaturally paced speech (TTS voice)
• Voice that doesn't match lip movements in the frames
• Unnatural pauses, breathing patterns, or speech transitions
• Synthetic-sounding background music
• Audio quality inconsistent with video quality
• Speaker mentioning AI tools or AI generation

State your audio assessment before the final verdict.

"""


def _build_prompt(caption: str | None, has_audio: bool = False) -> str:
    signal = _caption_signal(caption)

    if caption:
        if signal == "STRONG":
            signal_label = "⚠️ STRONG — caption explicitly mentions AI generation"
            signal_instruction = (
                "This is a near-definitive signal. Weight this very heavily toward AI GENERATED "
                "unless the visual evidence is overwhelmingly contradictory."
            )
        elif signal == "WEAK":
            signal_label = "⚡ WEAK — caption contains AI-related terms"
            signal_instruction = "Consider this as supporting evidence alongside visual analysis."
        else:
            signal_label = "— NEUTRAL — no AI keywords detected"
            signal_instruction = "Caption gives no direct signal either way."

        caption_block = _CAPTION_ANALYSIS_WITH_SIGNAL.format(
            caption=caption,
            signal_label=signal_label,
            signal_instruction=signal_instruction,
        ) + "\n"
    else:
        caption_block = "No caption provided — skip SIGNAL 1, rely on visual and audio only.\n\n"

    audio_hint = f"Audio provided: {'YES — analyse it in SIGNAL 3 below' if has_audio else 'NO — skip SIGNAL 3'}\n\n"
    audio_signal_block = _AUDIO_SIGNAL_BLOCK if has_audio else ""

    return _PROMPT_TEMPLATE.format(
        caption_block=caption_block,
        audio_hint=audio_hint,
        caption_analysis_instruction=caption_block.strip() if caption else "No caption — skip.",
        audio_signal_block=audio_signal_block,
    )


# ---------------------------------------------------------------------------
# Response parsing
# ---------------------------------------------------------------------------

def _parse_verdict(text: str) -> DetectionResult:
    verdict = confidence = reason = None
    for line in text.strip().splitlines():
        if line.startswith("VERDICT:"):
            verdict = line.replace("VERDICT:", "").strip()
        elif line.startswith("CONFIDENCE:"):
            confidence = line.replace("CONFIDENCE:", "").strip()
        elif line.startswith("REASON:"):
            reason = line.replace("REASON:", "").strip()

    if not all([verdict, confidence, reason]):
        logger.warning(f"Could not fully parse response: {text!r}")
        return DetectionResult(
            verdict="UNCERTAIN",
            confidence="LOW",
            reason="Could not parse model response clearly.",
            raw_response=text,
        )

    return DetectionResult(
        verdict=verdict,
        confidence=confidence,
        reason=reason,
        raw_response=text,
    )


# ---------------------------------------------------------------------------
# Caption-only fast-path override
# ---------------------------------------------------------------------------

def _caption_override(caption: str | None) -> DetectionResult | None:
    """
    If caption signal is STRONG, return an immediate AI GENERATED verdict
    with HIGH confidence — skip costly vision calls.
    Only used as a pre-check; vision still runs to confirm/add detail.
    Returns None if no strong signal detected.
    """
    # We don't short-circuit entirely — we let vision confirm.
    # This function is reserved for future use if needed.
    return None


# ---------------------------------------------------------------------------
# Model calls
# ---------------------------------------------------------------------------

def _build_gemini_config(model: str) -> types.GenerateContentConfig:
    extra = {}
    if model == "gemini-2.5-flash":
        extra["thinking_config"] = types.ThinkingConfig(thinking_budget=0)
    return types.GenerateContentConfig(
        max_output_tokens=500,  # increased to allow full step-by-step reasoning
        temperature=0.1,
        safety_settings=_SAFETY_SETTINGS,
        **extra,
    )


def _finish_reason(response) -> str:
    try:
        if response.prompt_feedback and response.prompt_feedback.block_reason:
            return f"PROMPT_BLOCKED({response.prompt_feedback.block_reason})"
        return str(response.candidates[0].finish_reason)
    except (AttributeError, IndexError, TypeError):
        return "UNKNOWN"


async def _call_gemini(
    image_parts: list[types.Part],
    model: str,
    caption: str | None = None,
    audio_path: str | None = None,
) -> tuple[DetectionResult | None, int, int]:
    has_audio = audio_path is not None
    parts: list[types.Part] = [types.Part.from_text(text=_build_prompt(caption, has_audio))]

    if audio_path:
        with open(audio_path, "rb") as f:
            parts.append(types.Part.from_bytes(data=f.read(), mime_type="audio/mpeg"))

    parts.extend(image_parts)

    response = await _get_gemini().aio.models.generate_content(
        model=model,
        contents=parts,
        config=_build_gemini_config(model),
    )

    text = response.text
    if text is None:
        reason = _finish_reason(response)
        logger.warning(f"Gemini {model} blocked. reason={reason}")
        return None, 0, 0

    usage = response.usage_metadata
    input_tokens = (usage.prompt_token_count or 0) if usage else 0
    output_tokens = (usage.candidates_token_count or 0) if usage else 0
    return _parse_verdict(text), input_tokens, output_tokens


async def _call_claude(
    frame_paths: list[str],
    caption: str | None = None,
    has_audio: bool = False,
) -> tuple[DetectionResult, int, int]:
    model = "claude-haiku-4-5-20251001"
    prompt = _build_prompt(caption, has_audio=False)
    if has_audio:
        prompt += "\nNote: Audio analysis is not available for this response — base your verdict on visual frames and caption only."
    content: list[dict] = [{"type": "text", "text": prompt}]

    for frame_path in frame_paths:
        with open(frame_path, "rb") as f:
            image_b64 = base64.standard_b64encode(f.read()).decode()
        content.append({
            "type": "image",
            "source": {"type": "base64", "media_type": "image/jpeg", "data": image_b64},
        })

    response = await _get_claude().messages.create(
        model=model,
        max_tokens=500,  # increased to allow full reasoning
        messages=[{"role": "user", "content": content}],
    )

    text = response.content[0].text if response.content else None
    if not text:
        return DetectionResult(
            verdict="UNCERTAIN",
            confidence="LOW",
            reason="Claude returned no response.",
            raw_response=None,
        ), 0, 0

    input_tokens = response.usage.input_tokens
    output_tokens = response.usage.output_tokens
    return _parse_verdict(text), input_tokens, output_tokens


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

async def detect_ai_video(
    frame_paths: list[str],
    caption: str | None = None,
    video_path: str | None = None,
) -> DetectionResult:
    """
    Multi-signal detection pipeline:
      - Caption pre-screened for AI keywords before vision calls
      - Structured prompt forces model to reason per-signal then synthesize
      - Three-tier model escalation: Flash-Lite → Flash → Claude Haiku

    Escalation logic:
      1. gemini-2.5-flash-lite  — fast and cheap
      2. gemini-2.5-flash       — if confidence is LOW
      3. claude-haiku-4-5       — if Gemini blocks (model-level refusal)
    """
    from services.audio_extractor import extract_audio_async

    signal = _caption_signal(caption)
    if caption:
        logger.info(f"Caption: {caption[:80]!r} → signal={signal}")

    # Extract audio
    audio_path: str | None = None
    if video_path:
        output_dir = os.path.dirname(frame_paths[0])
        try:
            audio_path = await extract_audio_async(video_path, output_dir)
        except Exception:
            logger.warning("Audio extraction failed — continuing without audio.", exc_info=True)

    has_audio = audio_path is not None

    # Build Gemini image parts
    image_parts: list[types.Part] = []
    for frame_path in frame_paths:
        with open(frame_path, "rb") as f:
            image_parts.append(types.Part.from_bytes(data=f.read(), mime_type="image/jpeg"))

    # Tier 1: Flash-Lite
    model = "gemini-2.5-flash-lite"
    result, input_tokens, output_tokens = await _call_gemini(image_parts, model, caption, audio_path)
    if result:
        logger.info(f"{model}: verdict={result.verdict} confidence={result.confidence} caption_signal={signal}")

    # Tier 2: Flash — escalate if low confidence OR caption signal is STRONG but verdict disagrees
    should_escalate = False
    if result:
        if result.confidence == "LOW":
            should_escalate = True
            logger.info("Low confidence — escalating to gemini-2.5-flash.")
        elif signal == "STRONG" and result.verdict != "AI GENERATED":
            should_escalate = True
            logger.info(
                f"Strong caption signal but verdict={result.verdict} — escalating to gemini-2.5-flash for confirmation."
            )

    if result and should_escalate:
        model = "gemini-2.5-flash"
        result, input_tokens, output_tokens = await _call_gemini(image_parts, model, caption, audio_path)
        if result:
            logger.info(f"{model}: verdict={result.verdict} confidence={result.confidence}")

    # Tier 3: Claude — if Gemini blocked at either tier
    if result is None:
        logger.info("Gemini blocked — falling back to Claude claude-haiku.")
        model = "claude-haiku-4-5-20251001"
        result, input_tokens, output_tokens = await _call_claude(frame_paths, caption, has_audio)
        logger.info(f"{model}: verdict={result.verdict} confidence={result.confidence}")

    input_cost, output_cost = _MODEL_COSTS.get(model, (0.30, 1.00))
    cost_usd = (input_tokens * input_cost + output_tokens * output_cost) / 1_000_000

    return result.model_copy(update={
        "model_used": model,
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "cost_usd": cost_usd,
    })
